"""The patient's state during a simulated journey, and the provenance attached to every generated quantity.

Every value the journey generates is a `sourced(...)` record: the value, where it came from, and how strong that source
is. Evidence levels, strongest first:

    protocol      stated in the compiled StudySpec (with its quote)
    evidence      estimated from registry results (a named evidence table and subgroup)
    parameter     a fitted parameter of an asset (safety, operational, V3)
    assumption    a documented modelling assumption (registered in ASSUMPTIONS; sensitivity-testable)
    unsupported   nothing supports a value: none is generated

Assumptions live only in ASSUMPTIONS, so the paper and the trace can list every one of them.
"""

from dataclasses import dataclass, field

LEVELS = ("protocol", "evidence", "parameter", "assumption", "unsupported")

ASSUMPTIONS = {
    "A1_ae_onset": "an adverse event's onset day is uniform over the patient's reporting window (first dose to 30 days after "
                   "the last dose): registries report cumulative incidence, not onset times",
    "A2_ae_grade": "a serious adverse event is recorded at grade 3 (the lowest grade consistent with seriousness for most "
                   "CTCAE terms); a non-serious event at grade 1 or 2 with equal probability; registries report seriousness, not grade",
    "A3_ae_resolution": "a grade 1-2 event resolves by the next scheduled visit after onset; a grade 3 or higher event by the "
                        "second: resolution is detected at visits",
    "A4_relatedness": "adverse events generated by the safety model are treated as related to study treatment when a dose "
                      "modification rule requires relatedness",
    "A5_lab_value_in_grade": "during a laboratory-type adverse event, the laboratory value is drawn uniformly within that "
                             "grade's CTCAE v5 range; outside events the baseline is carried forward",
    "A6_withdrawal_timing": "a withdrawal (subject decision, loss to follow-up, physician decision) occurs at a uniformly "
                            "distributed time over the patient's on-study period; its probability is from registry disposition",
    "A7_progression_exponential": "when progression-free survival comes from a reported median only, progression times "
                                  "are exponential with that median",
    "A8_resume_same_dose": "after a hold whose resume instruction the compiler could not type, treatment resumes at the "
                           "current dose level",
    "A9_supportive_care_given": "supportive care and prophylaxis are given as the protocol requires, so an adverse event that "
                                "occurs is one that occurred despite them",
    "A10_normal_baseline_labs": "laboratory values are within normal limits at baseline (patients met the protocol's organ "
                                "function criteria); rules for patients abnormal at baseline are not applied",
    "A11_grade3_clinically_significant": "an adverse event of grade 3 or higher is clinically significant where a rule requires it",
    "A12_reference_limits": "laboratory reference limits (LLN: neutrophils 2.0, platelets 150, white cells 4.0 x10^9/L; "
                            "hemoglobin 12.0 g/dL) are typical adult values; laboratories set their own",
    "A13_screening_day": "the screening visit takes place at the start of the protocol's screening window",
    "A14_ae_discontinuation": "beyond the protocol's own dose-modification rules, a patient stops treatment for an adverse event "
                              "with the registry participant-flow probability, at a uniform time over planned treatment; a stop "
                              "triggered by a protocol rule first takes precedence",
    "A15_death_timing": "death in the study period has the registry participant-flow probability and occurs at a uniform time "
                        "over the simulated horizon (registry flow periods span treatment and follow-up)",
    "A16_unknown_criteria_calibrated": "eligibility criteria the generated patients cannot answer pass independently, with one "
                                       "probability chosen so that the eligible share matches the registry screen pass rate",
    "A17_standard_3_plus_3": "when the protocol's escalation table cannot be compiled, the standard 3+3 table is simulated",
    "A18_participation_years": "with no stated censoring rate, the registry study-period withdrawal share is spread over 2 years",
    "A22_short_participation": "with no treatment cycles, participation ends after the last planned administration plus a 30-day "
                                "reporting window, and the registry's whole-trial exit shares are scaled by that duration over a year",
    "A23_cr_share": "when no complete-response input exists, complete responses are 15% of responses",
    "A24_tumour_dynamics": "response depth is uniform within its category band, nadir is reached by the second assessment, progression "
                           "is independent of response depth, and 35% of progressions are by a new lesion",
    "A25_recist_defaults": "when the protocol compiles no response thresholds, RECIST 1.1 is used (PR 30% decrease, PD 20% and 5 mm increase)",
    "A26_post_progression_survival": "death follows progression: post-progression survival is exponential with median equal to the "
                                     "arm's overall-survival input minus its progression median (at least 1 month; 12 months without "
                                     "an OS input); a patient who never progresses does not die of the disease within follow-up",
    "A27_subgroup_prevalence_equal": "a protocol subgroup factor whose levels no registry baseline table (nor the protocol) "
                                     "reports is split equally across its stated levels",
    "A28_prognostic_effects": "a subgroup effect from registry results by subgroup is prognostic: the same in every arm, "
                              "multiplicative on the progression hazard and the response odds, independent across factors, and "
                              "centred on the arm's patient mix so each arm's overall rate is unchanged",
    "A29_within_patient_correlation": "the two measurements of the same participant (one per exposure) are correlated on the log "
                                      "scale with correlation 0.5 when no source reports it (varied 0.3 and 0.7 in sensitivity)",
    "A21_day1_dosing": "an agent whose dosing days the protocol does not state is given on day 1 of each cycle",
    "A20_assessment_lag": "with no stated time point or treatment length, the primary assessment is 6 months after entry",
    "A19_unnamed_arm_is_comparator": "an arm that names no anticancer agent is the comparator: it receives the regimen of the "
                                     "arms without the investigational agent (the agent given in the most arms)",
}


def sourced(value, level: str, source: str, quote: str | None = None, assumption: str | None = None) -> dict:
    assert level in LEVELS, level
    assert level != "assumption" or assumption in ASSUMPTIONS, assumption
    out = {"value": value, "evidence_level": level, "source": source}
    if quote:
        out["quote"] = quote
    if assumption:
        out["assumption"] = assumption
    return out


@dataclass
class PatientState:
    subject_id: str
    arm_id: str
    enrollment_day: float
    baseline: dict
    day: int = 0
    on_treatment: bool = True
    on_study: bool = True
    dose: dict = field(default_factory=dict)            # agent -> current dose (value, unit) or level label
    reductions: dict = field(default_factory=dict)      # agent -> number of dose reductions
    held_until: dict = field(default_factory=dict)      # agent -> day treatment may resume (None: not held)
    held_since: dict = field(default_factory=dict)      # agent -> first day of the latest hold
    holds: list = field(default_factory=list)           # (agent, first held day, resume day)
    dose_history: list = field(default_factory=list)    # (day, agent, dose) after each change
    discontinued: dict = field(default_factory=dict)    # agent -> (day, reason)
    progression_day: int | None = None                  # true (latent) progression day
    progression_detected_day: int | None = None
    off_treatment: tuple | None = None                  # (day, reason)
    death_day: int | None = None
    off_study: tuple | None = None
    events: list = field(default_factory=list)          # the trace: one dict per clinical event, in time order
    attended: list = field(default_factory=list)        # (day, visit, planned items) of every visit attended (L064)
    required: list = field(default_factory=list)        # (day, visit, planned items, status) the protocol requires (L066)

    def log(self, day, visit, category, item, result, consequence="", **provenance):
        self.events.append({"day": int(day), "visit": visit, "category": category, "item": item, "result": result,
                            "consequence": consequence, **provenance})

    def active_agents(self) -> list[str]:
        return [a for a in self.dose if a not in self.discontinued]
