"""Which patient variables does each protocol's eligibility need, and which does the population generate?

For every development protocol, walk the compiled StudySpec's eligibility logic trees and list each leaf's variable,
its rule type, unit and bounds, whether the criterion is executable, and whether the locked population generates that
variable (a key present in the population records). The totals show which variables would turn the most UNDETERMINED
patients into decided ones, across protocols: the build list for new baseline variables comes from here, not from a
generic lab panel.

Output: data/validation/screening_variable_audit.csv and .md.
"""

import csv
import json
import re
import sys
from collections import Counter, defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def latest(study, kind):
    c = [p for p in (ROOT / "data/locked" / study).glob(f"{kind}_v*") if re.fullmatch(rf"{kind}_v[\d.]+", p.name)]
    return max(c, key=lambda p: tuple(int(x) for x in p.name.rsplit("_v", 1)[1].split("."))) if c else None


def leaves(node):
    if not isinstance(node, dict):
        return
    if node.get("node") == "LEAF":
        yield node
    for k in ("children", "operands", "args", "items"):
        for c in node.get(k) or []:
            yield from leaves(c)
    if node.get("child"):
        yield from leaves(node["child"])


def main():
    sys.stdout.reconfigure(encoding="utf-8")
    protocols = json.loads((ROOT / "data/manifest/development_protocols.json").read_text(encoding="utf-8"))["protocols"]
    rows = []
    for p in protocols:
        spec_lock, pop_lock = latest(p["id"], "studyspec"), latest(p["id"], "population")
        if not (spec_lock and pop_lock):
            continue
        spec = json.loads((spec_lock / "studyspec.json").read_text(encoding="utf-8"))
        generated = set()
        with open(pop_lock / "population.jsonl", encoding="utf-8") as fh:
            for i, line in enumerate(fh):
                generated |= set(json.loads(line))
                if i >= 200:
                    break
        for c in spec["eligibility"]:
            for leaf in leaves(c.get("logic")):
                var = leaf.get("variable") or (f"umls:{leaf['cui']}" if leaf.get("cui") else None)
                rows.append({"protocol": p["id"], "criterion_id": c["criterion_id"], "kind": c.get("kind"),
                             "criterion_status": c.get("status"), "variable": var, "canonical": leaf.get("canonical"),
                             "subject": leaf.get("subject"), "rule_type": leaf.get("rule_type"), "leaf_kind": leaf.get("kind"),
                             "unit": leaf.get("unit"), "lower": leaf.get("lower"), "upper": leaf.get("upper"),
                             "generated": bool(var and var in generated), "leaf_status": leaf.get("status")})

    out = ROOT / "data/validation"
    with open(out / "screening_variable_audit.csv", "w", newline="", encoding="utf-8") as fh:
        w = csv.DictWriter(fh, fieldnames=list(rows[0]))
        w.writeheader()
        w.writerows(rows)

    missing = [r for r in rows if r["criterion_status"] == "EXECUTABLE" and not r["generated"] and r["variable"]]
    by_rule = defaultdict(lambda: {"protocols": set(), "leaves": 0, "examples": Counter()})
    for r in missing:
        key = r["rule_type"] or r["leaf_kind"] or "other"
        by_rule[key]["protocols"].add(r["protocol"])
        by_rule[key]["leaves"] += 1
        by_rule[key]["examples"][r["canonical"] or r["subject"]] += 1
    per_protocol = defaultdict(lambda: Counter())
    for r in rows:
        per_protocol[r["protocol"]]["leaves"] += 1
        per_protocol[r["protocol"]]["executable"] += r["criterion_status"] == "EXECUTABLE"
        per_protocol[r["protocol"]]["generated"] += r["generated"]
        per_protocol[r["protocol"]]["executable_missing"] += r["criterion_status"] == "EXECUTABLE" and not r["generated"]
    lines = ["# Screening variables: needed by eligibility vs generated by the population", "",
             "Generated by `scripts/audit_missing_screening_variables.py` from the latest locked StudySpec and population of "
             "each development protocol. A leaf is one variable test inside a criterion's logic.", "",
             "| Protocol | Leaves | In executable criteria | Variable generated | Executable but variable missing |",
             "| --- | ---: | ---: | ---: | ---: |"]
    for k, v in per_protocol.items():
        lines.append(f"| {k} | {v['leaves']} | {v['executable']} | {v['generated']} | {v['executable_missing']} |")
    lines += ["", "## Missing variables in executable criteria, by rule type", "",
              "| Rule type | Protocols | Leaves | Most frequent variables |", "| --- | ---: | ---: | --- |"]
    for k, v in sorted(by_rule.items(), key=lambda kv: (-len(kv[1]["protocols"]), -kv[1]["leaves"])):
        ex = ", ".join(f"{n} ({c})" for n, c in v["examples"].most_common(6))
        lines.append(f"| {k} | {len(v['protocols'])} | {v['leaves']} | {ex} |")
    (out / "screening_variable_audit.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("\n".join(lines))


if __name__ == "__main__":
    main()
