"""COMPARISON.md generated from one run's canonical outputs and the trial's registry record (no hand-typed numbers).

Usage: python scripts/comparison_report.py NCT VERSION [OUT_DIR]

Simulated values come from the run's case-study summary (feasibility/case_study_summary.json) and feasibility.json;
registry values from data/holdout_comparison/<NCT>.json; scored comparisons from the run's comparison outputs:
  comparison/ratio_ni/ratio_ni_comparison.json          (compare-registry-ratio-ni)
  comparison/safety/safety_comparison.json              (compare-registry-safety)
  comparison/baseline/baseline_comparison.json          (compare-registry-baseline)
  comparison/control/control_external*.json             (predict-control-external)
A quantity missing from these files is reported as missing, never filled in.
"""

import json
import math
import re
import sys
from datetime import date
from pathlib import Path

from scipy import stats

NCT, VER = sys.argv[1], sys.argv[2]
RUN = Path("data/trial/runs") / NCT / f"v{VER}"
OUT = Path(sys.argv[3]) if len(sys.argv) > 3 else RUN / "feasibility"
LOCK = Path("data/locked") / NCT


def load(p: Path):
    return json.loads(p.read_text(encoding="utf-8")) if p.exists() else None


F = load(RUN / "feasibility" / "feasibility.json")
CS = load(RUN / "feasibility" / "case_study_summary.json")
CO, HE = CS["original_protocol"], CS["historical_evidence"]
REG = load(Path("data/holdout_comparison") / f"{NCT}.json")
RNI = load(RUN / "comparison" / "ratio_ni" / "ratio_ni_comparison.json")
SAF = load(RUN / "comparison" / "safety" / "safety_comparison.json")
BAS = load(RUN / "comparison" / "baseline" / "baseline_comparison.json")
CTL = load(RUN / "comparison" / "control" / "control_external.json")
CTR = load(RUN / "comparison" / "control" / "control_external_response.json")
PS, RS = REG["protocolSection"], REG.get("resultsSection") or {}


def pct(x, d=1):
    return "—" if x is None else f"{100 * x:.{d}f}%"


def ordinal(n: int) -> str:
    return f"{n}{'th' if 10 <= n % 100 <= 20 else {1: 'st', 2: 'nd', 3: 'rd'}.get(n % 10, 'th')}"


def short(label: str) -> str:
    """A plain arm name: the label up to its first comma or qualifying clause (as on the figures)."""
    return re.split(r",| [Ww]ith | [Cc]oformulated| [Aa]dministered", label)[0].strip()


def stamp(s):
    return (s or "").replace("+00:00", "Z")


# ---- registry facts ----
groups = (RS.get("adverseEventsModule") or {}).get("eventGroups") or []
ctl_title = (CTL or CTR or {}).get("control_group")
ctl_arm, exp_arm = (CTL or CTR or {}).get("control_arm"), (CTL or CTR or {}).get("experimental_arm")
reg_arm = {}                                     # simulated arm id -> registry adverse-event group
for g in groups:
    if ctl_title and g["title"] == ctl_title:
        reg_arm[ctl_arm] = g
    elif exp_arm:
        reg_arm[exp_arm] = g
base_meas = (RS.get("baselineCharacteristicsModule") or {}).get("measures") or []
total_gid = ((RS.get("baselineCharacteristicsModule") or {}).get("groups") or [{}])[-1].get("id")


def reg_baseline():
    out = {}
    for m in base_meas:
        title = m["title"].split(" (")[0].split(":")[0]
        for c in m.get("classes") or []:
            for cat in c.get("categories") or []:
                v = next((float(x["value"]) for x in cat["measurements"] if x["groupId"] == total_gid), None)
                if v is not None:
                    out[(title, cat.get("title"))] = v
    n = sum(v for (t, k), v in out.items() if t == "Sex" and k in ("Female", "Male"))
    return out, n


RB, RN = reg_baseline()
status = PS.get("statusModule") or {}
start = (status.get("startDateStruct") or {}).get("date")
pc = (status.get("primaryCompletionDateStruct") or {}).get("date")
enrolled = ((PS.get("designModule") or {}).get("enrollmentInfo") or {}).get("count")
window_years = (date.fromisoformat(pc) - date.fromisoformat(start)).days / 365.25 if start and pc and len(pc) == 10 else None
not_posted = [o["title"] for o in (RS.get("outcomeMeasuresModule") or {}).get("outcomeMeasures") or [] if o.get("reportingStatus") == "NOT_POSTED"]

L = [f"# Simulation of the final run against the trial's registry results", ""]
L.append("Generated by `scripts/comparison_report.py` from this run's case-study summary, feasibility output and comparison "
         "files, and the trial's ClinicalTrials.gov record. No number below is typed by hand.")
L.append("")
lock_times = sorted(stamp((load(p / "lock.json") or {}).get("locked_at")) for p in LOCK.glob(f"*_v{VER}") if (p / "lock.json").exists())
fetched = stamp((RNI or SAF or {}).get("registry_fetched_at"))
L.append(f"- **Run:** stages locked {' to '.join(dict.fromkeys(t[:10] for t in (lock_times[0], lock_times[-1]))) if lock_times else '—'}; "
         f"registry record fetched {fetched}. The ordering check reported by the comparison tools: "
         f"{'verified' if (RNI or {}).get('order_verified') else 'not verified (this run was locked after the registry record was fetched)'}.")
L.append(f"- **Registry status:** {status.get('overallStatus')}, started {start}, primary completion {pc}.")
if not_posted:
    L.append(f"- **Outcome measures listed but not posted:** {', '.join(t.split(' (')[0] for t in not_posted)}. These cannot be scored.")
L.append("")

# ---- 1. primary endpoints ----
L += ["## 1. Primary endpoints (ratio noninferiority)", ""]
if RNI:
    L += ["| Endpoint | Variability | Predicted P(noninferior) | Simulated ratio p10-p90 | Actual ratio (CI) | Actual noninferior | Conclusion agrees |",
          "| --- | --- | ---: | --- | --- | --- | --- |"]
    for it in RNI["items"]:
        if it["status"] != "SCORED":
            continue
        a = it["actual"]
        for s in it["scenarios"]:
            g = s["predicted_gmr"]
            L.append(f"| {it['endpoint']} | {s['variability']} | {s['predicted_p_success']:.3f} | {g['p10']:.2f}-{g['p90']:.2f} "
                     f"(actual at {s['actual_gmr_percentile']}) | {a['gmr']:.2f} ({a['ci_pct']}% CI {a['ci'][0]:.2f}-{a['ci'][1]:.2f}) | "
                     f"{'yes' if a['noninferior'] else 'no'} | {'yes' if it['conclusion_agrees'] else 'no'} |")
    L.append("")
    L += ["| Endpoint | Actual pooled CV | Comparable registry trials | Protocol power statement |", "| --- | ---: | ---: | ---: |"]
    cvs = [(HE.get("pk_cv_auc_registry"), HE.get("pk_cv_auc_protocol")), (HE.get("pk_cv_ctrough_registry"), HE.get("pk_cv_ctrough_protocol"))]
    for it, (r, p) in zip([i for i in RNI["items"] if i["status"] == "SCORED"], cvs, strict=False):
        L.append(f"| {it['endpoint']} | {pct(it['variability_actual']['pooled_geo_cv'], 0)} | {pct(r, 0)} | {pct(p, 0)} |")
    L.append("")
    L += ["| Endpoint | Required evaluable | Simulated evaluable (this run) | P(requirement met) | Actual evaluable |", "| --- | ---: | ---: | ---: | ---: |"]
    req = {w["endpoint"]: w.get("required") for w in F["evaluability"]}
    for (ep, ev), it in zip(CO["evaluable"].items(), [i for i in RNI["items"] if i["status"] == "SCORED"], strict=False):
        L.append(f"| {ep} | {req.get(ep) or '—'} | {ev} | {pct(CO['p_requirement'].get(ep))} | {sum(it['actual']['n'].values())} |")
else:
    L.append("Ratio-noninferiority comparison file missing for this run.")
L.append("")

# ---- 2. enrolment and baseline ----
L += ["## 2. Enrolment and baseline", ""]
D = CO.get("demographics") or {}
by_arm = CO.get("by_arm") or {}
sim_split = " / ".join(f"{v['n']}" for v in by_arm.values()) if by_arm else "—"
reg_split = " / ".join(str(g["seriousNumAtRisk"]) for g in groups)
rows = [("Enrolled", f"{CO['enrolled']}", f"{enrolled}"),
        ("Arm split (" + " / ".join(short(v.get("label", k)) for k, v in by_arm.items()) + ")" if by_arm else "Arm split", sim_split, reg_split),
        ("Age, mean", f"{D['age_mean']:.1f}" if D.get("age_mean") is not None else "—",
         next((f"{v:.1f}" for (t, k), v in RB.items() if t.startswith("Age") and k is None), "—")),
        ("Female", pct(D.get("female_share")), pct(RB.get(("Sex", "Female"), 0) / RN) if RN else "—")]
for race in ("White", "Asian", "Black or African American"):
    rows.append((race, pct((D.get("race_shares") or {}).get(race)), pct(RB.get(("Race", race), 0) / RN) if RN else "—"))
rows.append(("Hispanic or Latino", pct(D.get("hispanic_share")), pct(RB.get(("Ethnicity", "Hispanic or Latino"), 0) / RN) if RN else "—"))
L += ["| | Simulated enrolled patients | Actual |", "| --- | --- | --- |"] + [f"| {a} | {b} | {c} |" for a, b, c in rows]
L.append("")
if BAS:
    misses = [i["quantity"] for i in BAS["items"] if not i["inside_90"]]
    L.append(f"- Registry-level baseline predictor (90% interval for a trial of the registry's size, disease "
             f"{BAS['summary']['query'].get('disease_family')}): {BAS['summary']['inside_90']} of {BAS['summary']['scored']} quantities "
             f"inside; outside: {', '.join(misses) if misses else 'none'}.")
oa = CO.get("arm_split_outputs_stage")
if oa and by_arm and [oa.get(k) for k in by_arm] != [v["n"] for v in by_arm.values()]:
    L.append(f"- **Open inconsistency:** the outputs stage allocates {' / '.join(str(oa.get(k)) for k in by_arm)} while the journey and "
             f"analysis stages allocate {sim_split}; the stages do not yet share one randomisation.")
L.append("")

# ---- 3. accrual ----
L += ["## 3. Accrual", ""]
R = CO["recruitment"]
hl = F["recruitment"]["historical_lognormal"]
if enrolled and window_years:
    obs = enrolled / window_years
    pctile = stats.norm.cdf((math.log(obs) - hl["mu"]) / hl["sd"])
    p_window = 1 - stats.norm.cdf((math.log(F["target"] / window_years) - hl["mu"]) / hl["sd"])
    L += [f"- Comparable trials (historical accrual distribution): median {HE['recruitment_median_per_year']:.0f} patients/year.",
          f"- The protocol needs {R['required_per_year']:.0f}/year to finish in {R['planned_months']:.0f} months: the "
          f"{ordinal(round(100 * R['required_percentile']))} percentile of comparable trials; {pct(R['p_complete_in_planned_window'])} chance of "
          f"finishing in that window; median time to target {R['median_months']:.0f} months.",
          f"- Actual: {enrolled} enrolled within {window_years:.2f} years from start to primary completion, at least {obs:.0f}/year "
          f"(the window includes follow-up, so the true rate was higher). That rate sits at the {ordinal(round(100 * pctile))} percentile of the "
          f"historical distribution; the distribution gave {pct(p_window)} probability of reaching {F['target']} within that window."]
    if R["required_percentile"] >= 0.75 and pctile >= 0.75:
        L.append("- The plan needed upper-tail recruitment, and the trial achieved upper-tail recruitment.")
L.append("")

# ---- 4. safety ----
L += ["## 4. Safety", ""]
L += ["| | Simulated cohort incidence | Historical arm-level estimate | Actual |", "| --- | --- | --- | --- |"]
for aid, g in reg_arm.items():
    a = by_arm.get(aid) or {}
    L.append(f"| Any serious AE, {short(a.get('label', aid))} | {pct(a.get('sae_rate'))} ({a.get('sae_count', '—')}/{a.get('n', '—')}) | "
             f"{pct(HE.get('sae_rate_arm_level'))} | {pct(g['seriousNumAffected'] / g['seriousNumAtRisk'])} ({g['seriousNumAffected']}/{g['seriousNumAtRisk']}) |")
tot_k = sum(g["seriousNumAffected"] for g in groups)
tot_n = sum(g["seriousNumAtRisk"] for g in groups)
L.append(f"| Any serious AE, all patients | {pct(CO['sae_rate_simulated'])} ({CO['sae_count_simulated']}/{CO['enrolled']}) | "
         f"{pct(HE.get('sae_rate_arm_level'))} | {pct(tot_k / tot_n) if tot_n else '—'} ({tot_k}/{tot_n}) |")
for aid, g in reg_arm.items():
    a = by_arm.get(aid) or {}
    L.append(f"| Deaths, {short(a.get('label', aid))} | {pct(a.get('death_rate'))} (at the simulated data cut-off) | — | "
             f"{pct(g['deathsNumAffected'] / g['deathsNumAtRisk'])} ({g['deathsNumAffected']}/{g['deathsNumAtRisk']}, over the AE reporting period) |")
L.append("")
L.append("- Deaths are not on a matched follow-up window: the simulated count is at the simulated data cut-off, the registry "
         "count covers the adverse-event reporting period.")
if SAF:
    rows_ = [r for r in SAF["rows"] if r.get("observed_listed")]
    misses = [r["term"].replace("_", " ") for r in rows_ if not r["inside_90"]]

    def mae(ser):
        e = sorted(abs(r["predicted_rate"] - r["observed"] / r["at_risk"]) for r in rows_ if r["seriousness"] == ser)
        return (e[len(e) // 2] if e else None), len(e), sum(r["predicted_rate"] > r["observed"] / r["at_risk"] for r in rows_ if r["seriousness"] == ser)

    ms, ns, _ = mae("serious")
    mn, nn, over = mae("non_serious")
    widths = sorted(r["predicted_90"][1] - r["predicted_90"][0] for r in rows_)
    L += [f"- **Per event** ({SAF['matched_terms']} terms matched, pooled arms): {SAF['matched_inside_90']} of {SAF['matched_terms']} inside the "
          f"90% predictive interval; {SAF['unlisted_inside_90']} of {SAF['unlisted_predicted_terms']} predicted-but-unlisted terms consistent. "
          f"Outside: {', '.join(misses) if misses else 'none'}.",
          f"- Median absolute error: serious events {pct(ms)} ({ns} terms); non-serious events {pct(mn)} ({nn} terms, {over} over-predicted). "
          f"Median 90% interval width {widths[len(widths) // 2] if widths else '—'} of {SAF['registry_at_risk']} patients.",
          f"- Registry terms not predicted: {len(SAF['unpredicted_registry_terms'])}."]
L.append("")

# ---- 5. response ----
L += ["## 5. Objective response", ""]
L += ["| Arm | Evidence input (disease-first hierarchy) | Simulated best overall response (CR+PR) | Actual |", "| --- | --- | --- | --- |"]
for aid, a in by_arm.items():
    r = a.get("response") or {}
    inp = r.get("input") or {}
    ci = inp.get("ci95") or [None, None]
    sci = r.get("ci95") or [None, None]
    L.append(f"| {short(a.get('label', aid))} | {pct(inp.get('value'))} (95% CI {pct(ci[0])}-{pct(ci[1])}; {inp.get('level', '—')}; {inp.get('source', '—')}) | "
             f"{pct(r.get('rate'))} ({r.get('responders', '—')}/{r.get('n', '—')}; 95% CI {pct(sci[0])}-{pct(sci[1])}) | not posted |")
L.append("")


# ---- 6. control-arm benchmark ----
def ctl_table(doc, outcomes):
    out = ["| Method | " + " | ".join(f"{lab}: predicted mean (95% interval)" for _, lab in outcomes) + " |",
           "| --- | " + " | ".join("---" for _ in outcomes) + " |"]
    rows_ = [r for r in doc["rows"] if r["population"] == "registry_experimental"]
    obs = []
    for key, _ in outcomes:
        r = next((x for x in rows_ if x["outcome"] == key), None)
        obs.append(f"**{pct(r['observed'])} ({r['k']}/{r['n']})**" if r and r.get("observed") is not None else "not posted")
    out.append("| **Actual control arm** | " + " | ".join(obs) + " |")
    for m in dict.fromkeys(r["method"] for r in rows_):
        cells = []
        for key, _ in outcomes:
            r = next((x for x in rows_ if x["outcome"] == key and x["method"] == m), None)
            cells.append("—" if not r else f"{pct(r['predicted'], 0)} ({100 * r['lower']:.0f}-{100 * r['upper']:.0f})"
                         + (", **miss**" if r.get("covered") is False else ""))
        out.append(f"| {m} | " + " | ".join(cells) + " |")
    return out


L += ["## 6. Hidden-control benchmark on the trial's control arm", ""]
if CTL or CTR:
    c = CTL or CTR
    L.append(f"Control arm: {c['control_group']}. Context: {c['context']['family']}, {c['context']['phase']}, classes "
             f"{', '.join(c['context']['classes'])}, start {c['context']['year']}, region {c['context']['region']}. Population: the "
             "experimental arm's posted baseline. Each method predicts the control arm without seeing it.")
    L.append("")
if CTL:
    L += ctl_table(CTL, [("serious_ae", "Serious AE"), ("death", "Deaths")]) + [""]
if CTR:
    L += ctl_table(CTR, [(CTR["rows"][0]["outcome"], "Objective response")]) + [""]
    a = by_arm.get(ctl_arm) or {}
    r = a.get("response") or {}
    if r.get("rate") is not None:
        L.append(f"- Simulated control-arm response (this run): {pct(r['rate'])} ({r['responders']}/{r['n']}); evidence input "
                 f"{pct((r.get('input') or {}).get('value'))}.")
L.append("")
L.append("One trial is one draw: each method's calibration is the cross-validated benchmark over the corpus.")
L.append("")

OUT.mkdir(parents=True, exist_ok=True)
(OUT / "COMPARISON.md").write_text("\n".join(L) + "\n", encoding="utf-8")
print(OUT / "COMPARISON.md")
