"""The share of patients with any serious adverse event, scored as a predictive count at the registry's sample size.

Comparing "58.8% predicted vs 2/7 observed" ignores that 7 patients carry almost no information. Here the locked
subgroup estimate of each arm (headline estimate, its 95% CI and the between-study heterogeneity tau on the logit scale)
defines the predictive distribution of a new trial's true rate:

    logit p ~ Normal(logit(estimate), se^2 + tau^2),   se = (logit(ci95_hi) - logit(ci95_lo)) / 3.92

and the registry's count Y of patients with a serious event among its n at risk is Y | p ~ Binomial(n, p). With several
simulated arms (the registry aggregate pools them), p is the mean of the arms' rates, drawn with a shared
between-study deviation (arms of one trial share its reporting practice). Monte Carlo, 400,000 draws.

Reported per trial: P(Y = y), the log score, the two-sided mid-p predictive tail, the PIT, and the central 90%
predictive interval of Y. Output: data/validation/ae_predictive_scores.csv and .md.
"""

import csv
import json
import math
import re
import sys
from pathlib import Path

import numpy as np
from scipy import special, stats

ROOT = Path(__file__).resolve().parents[1]
DRAWS = 400_000


def latest(study, kind):
    c = [p for p in (ROOT / "data/locked" / study).glob(f"{kind}_v*") if re.fullmatch(rf"{kind}_v[\d.]+", p.name)]
    return max(c, key=lambda p: tuple(int(x) for x in p.name.rsplit("_v", 1)[1].split("."))) if c else None


def arm_params(h):
    lo, hi = (special.logit(np.clip(v, 1e-6, 1 - 1e-6)) for v in h["ci95"])
    se = (hi - lo) / 3.92
    return float(special.logit(h["estimate"])), float(math.sqrt(se ** 2 + (h.get("between_study_tau_logit") or 0.0) ** 2))


def main():
    sys.stdout.reconfigure(encoding="utf-8")
    protocols = json.loads((ROOT / "data/manifest/development_protocols.json").read_text(encoding="utf-8"))["protocols"]
    rng = np.random.default_rng(20260929)
    rows = []
    for p in protocols:
        out_lock, saf_lock = latest(p["id"], "outputs"), latest(p["id"], "safety_comparison")
        if not (out_lock and saf_lock):
            continue
        est = json.loads((out_lock / "trial_outputs.json").read_text(encoding="utf-8"))["feasibility"].get("subgroup_estimates") or {}
        heads = {}
        for arm, v in (est.get("arms") or {}).items():
            sae = v.get("serious_adverse_event") or {}
            if sae.get("status") == "RESOLVED":
                heads[arm] = {**sae["headline"], "subgroup": sae.get("headline_subgroup")}
        agg = json.loads((saf_lock / "safety_comparison.json").read_text(encoding="utf-8")).get("aggregate", {}).get("serious")
        if not heads or not agg:
            continue
        y, n = agg["registry_affected"], agg["at_risk"]
        distinct = list({(round(h["estimate"], 9), round(h["ci95"][0], 9)): h for h in heads.values()}.values())
        z = rng.standard_normal(DRAWS)
        pbar = np.mean([special.expit(m + s * z) for m, s in map(arm_params, distinct)], axis=0)
        pmf_y = float(np.mean(stats.binom.pmf(y, n, pbar)))
        below = float(np.mean(stats.binom.cdf(y - 1, n, pbar))) if y > 0 else 0.0
        above = 1.0 - below - pmf_y
        ysim = rng.binomial(n, pbar)
        rows.append({
            "protocol": p["id"], "nct_id": p["nct_id"], "outputs_lock": out_lock.name, "distinct_arm_estimates": len(distinct),
            "headline_subgroups": "; ".join(sorted({h["subgroup"] or "" for h in distinct})),
            "arms": len(heads),
            "predicted_rate": round(float(np.mean(pbar)), 4),
            "predicted_rate_80": f"{np.quantile(pbar, 0.1):.2f}-{np.quantile(pbar, 0.9):.2f}",
            "observed": f"{y}/{n}", "observed_rate": round(y / n, 4),
            "predictive_90_count": f"{int(np.quantile(ysim, 0.05))}-{int(np.quantile(ysim, 0.95))}",
            "p_observed_count": round(pmf_y, 5), "log_score": round(math.log(max(pmf_y, 1e-300)), 3),
            "pit_mid": round(below + 0.5 * pmf_y, 4),
            "two_sided_mid_p": round(min(1.0, 2 * min(below + 0.5 * pmf_y, above + 0.5 * pmf_y)), 4),
            "inside_90": bool(np.quantile(ysim, 0.05) <= y <= np.quantile(ysim, 0.95)),
        })

    out = ROOT / "data/validation"
    with open(out / "ae_predictive_scores.csv", "w", newline="", encoding="utf-8") as fh:
        w = csv.DictWriter(fh, fieldnames=list(rows[0]))
        w.writeheader()
        w.writerows(rows)
    lines = ["# Any serious adverse event: predictive count at the registry's sample size", "",
             "Generated by `scripts/score_ae_predictive.py` from the locked subgroup estimates and safety comparisons. "
             "Development protocols (results read before or during development): exploratory.", "",
             "| Protocol | Predicted rate (80%) | Observed | Predictive 90% for the count | P(observed count) | Two-sided mid-p | Inside 90% |",
             "| --- | --- | --- | --- | ---: | ---: | --- |"]
    for r in rows:
        lines.append(f"| {r['protocol']} | {r['predicted_rate']:.1%} ({r['predicted_rate_80']}) | {r['observed']} | "
                     f"{r['predictive_90_count']} | {r['p_observed_count']:.3f} | {r['two_sided_mid_p']:.2f} | {r['inside_90']} |")
    lines += ["", f"Inside the central 90% predictive interval: {sum(r['inside_90'] for r in rows)} of {len(rows)}. "
              "A small two-sided mid-p (below 0.10) marks a count the forecast made unlikely; with n = 7 or fewer, even a large "
              "rate error rarely reaches that."]
    (out / "ae_predictive_scores.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("\n".join(lines))


if __name__ == "__main__":
    main()
