"""Accrual forecasts scored with the right likelihood for what the registry tells us.

The locked planning comparison of each evaluated protocol holds the pipeline's accrual-rate forecast (a log-normal
reconstructed from the locked q10/median/q90) and the registry observation:

* REGISTRY_INTERVAL windows (start to primary completion) include follow-up after the last patient, so the true rate R
  satisfies R >= L = enrolled / window. The forecast is scored by P(R >= L) (the censored log score is its log); no
  point error is computed, because R is not observed.
* RECRUITMENT windows (verified recruitment dates) give the rate itself: scored by its predictive percentile (PIT) and
  the log density.

The protocol's own planning rate is classified against the same observation: with a lower bound only, a planning rate
at or above L cannot be distinguished from the truth ("consistent"); a planning rate below L is contradicted.
Trials with fewer than 5 patients enrolled are reported but marked not scoreable.

Output: data/validation/accrual_censored_scores.csv and .md.
"""

import csv
import json
import math
import re
from pathlib import Path

from scipy import stats

ROOT = Path(__file__).resolve().parents[1]
MIN_ENROLLED = 5


def latest(study, kind):
    c = [p for p in (ROOT / "data/locked" / study).glob(f"{kind}_v*") if re.fullmatch(rf"{kind}_v[\d.]+", p.name)]
    return max(c, key=lambda p: tuple(int(x) for x in p.name.rsplit("_v", 1)[1].split("."))) if c else None


def main():
    import sys
    sys.stdout.reconfigure(encoding="utf-8")
    protocols = json.loads((ROOT / "data/manifest/development_protocols.json").read_text(encoding="utf-8"))["protocols"]
    rows = []
    for p in protocols:
        lock = latest(p["id"], "planning_comparison")
        if lock is None:
            continue
        d = json.loads((lock / "planning_comparison.json").read_text(encoding="utf-8"))
        a, h = d["actual"], d["historical_model"]
        if h.get("status") != "SCORED":
            continue
        mu, sg = h["reconstruction"]["mu"], h["reconstruction"]["sigma"]
        rate = h["observed_rate_per_year_lower_bound"]
        censored = (a.get("window_kind") or "").startswith("REGISTRY_INTERVAL")
        z = (math.log(rate) - mu) / sg
        r = {"protocol": p["id"], "nct_id": d["nct_id"], "lock": str(lock.relative_to(ROOT)).replace("\\", "/"),
             "status": a["overall_status"], "enrolled": a["enrolled"], "window_years": round(a["window_years"], 3),
             "observation": "lower bound (registry interval incl. follow-up)" if censored else "rate (verified recruitment window)",
             "observed_rate_per_year": round(rate, 3), "forecast_median": round(math.exp(mu), 3),
             "forecast_80": f"{math.exp(mu - 1.2816 * sg):.1f}-{math.exp(mu + 1.2816 * sg):.1f}",
             "scoreable": a["enrolled"] >= MIN_ENROLLED}
        if censored:
            tail = float(stats.norm.sf(z))
            r.update({"p_rate_at_least_observed": round(tail, 4), "censored_log_score": round(math.log(tail), 4),
                      "pit": None, "log_density": None})
        else:
            r.update({"p_rate_at_least_observed": None, "censored_log_score": None, "pit": round(float(stats.norm.cdf(z)), 4),
                      "log_density": round(float(stats.norm.logpdf(z) - math.log(sg) - math.log(rate)), 4)})
        plans = [s for s in d["protocol_scenarios"] if s.get("patients_per_year")]
        verdicts = []
        for s in plans:
            pr = s["patients_per_year"]
            if censored:
                verdicts.append(f"{pr:g}/y: " + ("consistent (cannot be distinguished from a lower bound)" if pr >= rate
                                                 else "contradicted (below the observed lower bound)"))
            else:
                verdicts.append(f"{pr:g}/y: {pr / rate:.2f}x the observed rate")
        r["protocol_rates"] = "; ".join(verdicts) if verdicts else "none stated"
        rows.append(r)

    out = ROOT / "data/validation"
    with open(out / "accrual_censored_scores.csv", "w", newline="", encoding="utf-8") as fh:
        w = csv.DictWriter(fh, fieldnames=list(rows[0]))
        w.writeheader()
        w.writerows(rows)
    lines = ["# Accrual forecasts, scored as censored where the registry gives only a lower bound", "",
             "Generated by `scripts/score_censored_accrual.py` from the locked planning comparisons. Development protocols "
             "(results read before or during development; see `leakage_audit.md`): exploratory, not forecasts.", "",
             "| Protocol | Enrolled | Observation | Observed (patients/y) | Forecast median (80%) | Score | Protocol's planning rate |",
             "| --- | ---: | --- | ---: | --- | --- | --- |"]
    for r in rows:
        score = (f"P(R ≥ observed) = {r['p_rate_at_least_observed']:.2f}" if r["p_rate_at_least_observed"] is not None
                 else f"PIT = {r['pit']:.2f}")
        if not r["scoreable"]:
            score += " (not scoreable: < 5 enrolled)"
        lines.append(f"| {r['protocol']} | {r['enrolled']} | {'≥' if r['pit'] is None else '='} | {r['observed_rate_per_year']:.1f} | "
                     f"{r['forecast_median']:.1f} ({r['forecast_80']}) | {score} | {r['protocol_rates']} |")
    lines += ["", "**Reading.** P(R ≥ observed) is the forecast's probability of what the registry shows; values near 0 mean the "
              "forecast was too slow. A lower bound cannot show a forecast was too fast. For a planning rate, only a value "
              "below the lower bound is evidence against it."]
    (out / "accrual_censored_scores.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("\n".join(lines))


if __name__ == "__main__":
    main()
